### ISSUE TITLE
me sirvio para limpiar un conjunto de datos

### ISSUE THREAD

**Issue by pachadotdev** [Eitol/servel_scraper#2]
hola

esto no es un issue propiamente tal, pero lo que hice hace muchos anios aca https://github.com/pachadotdev/datachile-data/blob/master/elecciones/padron-electoral-2017/01-descargar.R ya no funciona pues ya no suben el xml

ahora tenia que separar de la mejor forma posible un listado de personas naturales y juridicas para un trabajo de donaciones a ONG y Fundaciones y tu script me sirvio para poder sacar a un monton de personas naturales del listado y quedarme con algunas personas y las empresas, lo que ahora podre limpiar con Excel

muchas gracias

**Comment by Eitol** [comment]
gracias!
